name: "Compile C/C++"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Compile C files
        run: |
          for FILE in $(git ls-files '*.c'); do gcc $FILE; done
      - name: Compile C++ files
        run: |
          for FILE in $(git ls-files '*.cpp'); do g++ -std=c++11 $FILE; done
